#!/bin/bash

# xmonad startup script. Intended to be run from an xsession configuration to
# run xmonad and some associated programs
#
# by Andy Holt
# 
# based on config of David Brewer
# (https://github.com/davidbrewer/xmonad-ubuntu-conf)

#
# GENERAL INITIALISATION
# 

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# start compositing to support transparency
xcompmgr -n &

#
# SCREEN CONFIGURATION
#

# handle screen config using xrandr
xrandr --output LVDS --auto --primary

# if find a screen connected via VGA, activate it and position to left of
# primary
xrandr | grep 'VGA-1 connected' | ifne xrandr --output VGA-1 --auto \
    --left-of LVDS

# if find a screen connected via DVI, activate it and position to left of
# primary
xrandr | grep 'DP-1 connected' | ifne xrandr --output DP-1 --auto --left-of LVDS

#
# LOAD SCREEN BACKGROUNDS
#

#xpmroot ~/Pictures/Romans_SaturnMoon2bg.png
nitrogen --restore &

#
# STARTUP ICON TRAY
#

# use trayer to create an icon tray at top right of screen
trayer \
    --edge top \
    -- align right \
    --SetDockType true \
    --SetPartialStrut true \
    --expand true \
    --width 10 \
    --transparent true \
    --tint 0x0c0a0b \
    --height 17 \
    &

# run gnome-keyring-daemon to avoid issues might otherwise encounter when using
# gnome applications which expect access to keyring. Prevents prompts might
# otherwise get for invalid certificates etc
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# now start xmonad
exec xmonad
